define({
    lblRegAccount: "Register - Create Account",
    lblRequiredFields1: "Field marked with ",
    lblRequiredFields2: " are compulsory fields",
    lblUserName: "UserName",
    lblEmail: "E-Mail ID",
    lblAltEmail: "Alternative E-Mail ID",
    lblPhone: "Your Phone",
    lblCountryCode: "Country Code",
    lblCityCode: "City Code",
    lblPhoneNumber: "Phone Number",
    lblPostalAddress: "Your Postal Address",
    lblCountry: "Country",
    lblSelectOne: "---------------- Select One ----------------",
    lblPassword: "Password",
    lblConfirmPassword: "Confirm Password",
    lblTerms1: "I accept the ",
    lblTerms2: "Terms of use",
    lblContinue: "Continue >>",
    lblReset: "Reset",
    msgFormInvalid: "Please correct, the input data are invalid",
    msgPassInvalid: "Please correct, the passwords are not equal",
    msgTermsNotAccepted: "Please accept the Terms of Use to continue",

    lblSuccesRegister: "Successful registration",
    lblBack: "Back"
});
